// <auto-generated />
namespace EF_CodeFirst_University.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class st : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(st));
        
        string IMigrationMetadata.Id
        {
            get { return "201910111240297_st"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
